<?php
/**
 * Sends product view data to Google Enhanced Ecommerce Analytics
 *
 * @author  Dale Owen @mediotype
 * @reference   https://developers.google.com/analytics/devguides/collection/analyticsjs/enhanced-ecommerce
 * @var $this Mage_Wishlist_Block_Customer_Wishlist
 */
$items = $this->getWishlistItems();
?>
<?php if($this->hasWishlistItems()): ?>
    <script type="text/javascript">
        //<![CDATA[
        <?php $position = 0 ?>
        <?php foreach($items as $item): ?>
        <?php $product = Mage::getModel('catalog/product')->load($item->getData('product_id')); ?>
        ga('ec:addImpression', {
            'id': '<?php echo $product->getId() ?>',
            'name': "<?php echo $product->getName() ?>",
            <?php if($product->getManufacturer()): ?>
            'brand': "<?php echo $product->getManufacturer() ?>",
            <?php endif; ?>
            'list': 'Wishlist',
            'position': '<?php echo ++$position ?>'
        });
        //add click analysis to the links
        var links = $$('#wishlist-table tbody tr:nth-child(<?php echo $position ?>) a');
        links.each(function(link){
            if(!link.hasClassName('btn-remove')){
                link.onclick = function() {
                    var productFieldObject = {
                        'id': '<?php echo $product->getId() ?>',
                        'name': "<?php echo $product->getName() ?>",
                        <?php if($product->getManufacturer()): ?>
                        'brand': "<?php echo $product->getManufacturer() ?>",
                        <?php endif; ?>
                        'position': '<?php echo $position ?>'
                    };
                    ga('ec:addProduct', productFieldObject);
                    ga('ec:setAction', 'click',{list: 'Cross Sell Products'});
                    ga('send', 'event', 'UX', 'click', 'Cross Sell Products',{
                        'hitCallback': function() {
                            document.location = link.href;
                        }
                    });
                };
            }
        });
        //add click analysis to add to cart
        var button = $('wishlist-table').down('tbody tr', <?php echo $position - 1 ?>).down('.btn-cart');
        button.originonclick = button.onclick;
        button.onclick = function() {
            ga('ec:addProduct', {
                'id': '<?php echo $product->getId(); ?>',
                'name': "<?php echo $product->getName(); ?>",
                <?php if($product->getManufacturer()): ?>
                'brand': "<?php echo $product->getManufacturer() ?>",
                <?php endif; ?>
                'price': '<?php echo $product->getPrice(); ?>',
                'quantity': '<?php echo $item->getData('qty') ?>'
            });
            ga('ec:setAction', 'add');
            button.onclick = button.originonclick;
            ga('send', 'event', 'UX', 'click', 'add to cart',{
                'hitCallback': function() {
                    button.click(button.originonclick);
                }
            });
        };

        <?php endforeach; ?>
        //]]>
    </script>
<?php endif; ?>
