<?php
/**
 * Sends product view data to Google Enhanced Ecommerce Analytics
 *
 * @author  Dale Owen @mediotype
 * @reference   https://developers.google.com/analytics/devguides/collection/analyticsjs/enhanced-ecommerce
 * @var $this Mage_Catalog_Block_Product_List_Upsell
 */
$items = $this->getItems();
$current_category = Mage::registry('current_category');
?>
<?php if(count($this->getItemCollection()->getItems())): ?>
    <script type="text/javascript">
        //<![CDATA[
        <?php $position = 0 ?>
        <?php $this->resetItemsIterator() ?>
        <?php for($_i=0;$_i<$this->getRowCount();$_i++): ?>
            <?php for($_j=0;$_j<$this->getColumnCount();$_j++): ?>
                <?php if($item=$this->getIterableItem()): ?>
                ga('ec:addImpression', {
                    'id': '<?php echo $item->getId() ?>',
                    'name': "<?php echo $item->getName() ?>",
                    <?php if($current_category): ?>
                    'category': "<?php echo $current_category->getName() ?>",
                    <?php endif; ?>
                    'list': 'Upsell Products',
                    'position': '<?php echo ++$position ?>'
                });
                //add click analysis to the links
                var links = $$('#upsell-product-table tr:nth-child(<?php echo $_i + 1 ?> td:nth-child(<?php echo $_j + 1 ?>) a');
                links.each(function(link){
                    link.onclick = function() {
                        console.log('click worked');
                        var productFieldObject = {
                            'id': '<?php echo $item->getId() ?>',// Product ID (string).
                            'name': "<?php echo $item->getName() ?>",
                            <?php if($current_category): ?>
                            'category': "<?php echo $current_category->getName() ?>",
                            <?php endif; ?>
                            'position': '<?php echo $position ?>'
                        };
                        ga('ec:addProduct', productFieldObject);
                        ga('ec:setAction', 'click',{list: 'Upsell Products'});
                        ga('send', 'event', 'UX', 'click', 'Upsell Products',{
                            'hitCallback': function() {
                                document.location = link.href;
                            }
                        });
                    };
                });
                <?php endif; ?>
            <?php endfor; ?>
        <?php endfor; ?>
        //]]>
    </script>
<?php endif; ?>
