
<?php
$prefix = Mage::getConfig()->getTablePrefix();
$connection = Mage::getSingleton('core/resource')->getConnection('core_write');
$prefix = Mage::getConfig()->getTablePrefix();
$tblname=$prefix.'mksstorelocator'; 
$sql1 = $connection->query("select * from $tblname order by id limit 1" ); 
$row1 = $sql1->fetch();
$latitudex = $row1['lat'];
$longitudex = $row1['longt'];
$addressx = $row1['address'];
$radius = $row1['radius'];

?>

<script src="http://code.jquery.com/jquery-1.10.2.min.js" type="text/javascript"></script> 
<script src="https://maps.google.com/maps/api/js?sensor=false" type="text/javascript"></script> 
<script type="text/javascript">

function map_xxx(x,y,z,a)
{

var miles = 3;
	var latitude = x; // parseFloat("26.850883100000000000");
	var longitude  = y; // parseFloat("75.824783600000040000");
        var address  = z; // "Rohini, New Delhi, Delhi, India";
        var radius  = a; // "Rohini, New Delhi, Delhi, India";
   
	var latlngPos = new google.maps.LatLng(latitude,longitude);
        
        // Set up options for the Google map
        var map = new google.maps.Map(document.getElementById("map"), {
            zoom: 14,

            center: latlngPos,
            mapTypeId: google.maps.MapTypeId.ROADMAP
        });    
        // draw circle

         var circle = new google.maps.Circle({
            center: latlngPos,
            radius: miles *radius,
            fillColor: "#ff69b4",
            fillOpacity: 0.2,
            strokeOpacity: 0.0,
            strokeWeight: 0,
            map: map
        });
               
} google.maps.event.addDomListener(window, 'load', initialize);
</script>



