<?php   $enable=$this->getStorelocatorEnabled();   ?>
<?php   $name=$this->getStorelocatorName();   ?>
<?php   $address=$this->getStorelocatorAddress();   ?>
<?php   $zipcode=$this->getStorelocatorZipcode();   ?>
<?php   $city=$this->getStorelocatorCity();   ?>
<?php   $country=$this->getStorelocatorCountry();   ?>
<?php   $phone=$this->getStorelocatorPhone();   ?>
<?php   $fax=$this->getStorelocatorFax();   ?>
<?php   $description=$this->getStorelocatorDescription();   ?>
<?php   $email=$this->getStorelocatorEmail();   ?>
<?php   $tradinghours=$this->getStorelocatorTradinghours();   ?>
<?php   $image=$this->getStorelocatorImage();   ?>
<?php   $stireurl=$this->getStorelocatorStoreurl();   ?>

<?php if($enable==1) { ?>
<?php
$prefix = Mage::getConfig()->getTablePrefix();
$connection = Mage::getSingleton('core/resource')->getConnection('core_write');
$prefix = Mage::getConfig()->getTablePrefix();
$tblname=$prefix.'mksstorelocator';
$sql1 = $connection->query("select * from $tblname order by id limit 1" );
$row1 = $sql1->fetch();
$latitudex = $row1['lat'];
$longitudex = $row1['longt'];
$addressx = $row1['address'];
$radiusx = $row1['radius'];
if($radiusx!='')
{
$radius = $row1['radius'];
}
else
{
$radius = '250';
}
?>
<script src="http://code.jquery.com/jquery-1.10.2.min.js" type="text/javascript"></script>
<script src="https://maps.google.com/maps/api/js?sensor=false" type="text/javascript"></script>
<script type="text/javascript">
function map_xxx(x,y,a)
{
var miles = 3;
    var latitude = x; // latitude code define ("26.850883100000000000");
    var longitude  = y; // longitude code define ("75.824783600000040000");
var radius  = a; // "radius area define";

    var latlngPos = new google.maps.LatLng(latitude,longitude);

// Set up options for the Google map
var map = new google.maps.Map(document.getElementById("map"), {
zoom: 14,
center: latlngPos,
mapTypeId: google.maps.MapTypeId.ROADMAP
});
// draw circle
var circle = new google.maps.Circle({
center: latlngPos,
radius: miles *radius,
fillColor: "#ff69b4",
fillOpacity: 0.2,
strokeOpacity: 0.0,
strokeWeight: 0,
map: map
});

} google.maps.event.addDomListener(window, 'load', initialize);
</script>
<body onload="map_xxx('<?php  echo $latitudex ?>','<?php echo $longitudex; ?>','<?php echo $radius; ?>');">
    <?php  $sql = $connection->query("select * from $tblname where status='0'" ); ?>
    <?php  //require_once 'app/design/frontend/base/default/template/storelocator/config.phtml'; ?>
    <div id="map_xxx" style="width:900px; border:10px;">
    <input class="search" placeholder="Search Name,Zip or Address" style="width:40%;"/>
        <ul class="list" style="height: 500px;overflow: auto;display:block;float: left;width: 43%;clear: left;" >
            <?php
            while($row = $sql->fetch())
            {
            if($row['radius']!='')
            {
            $rowradius = $row['radius'];
            }
            else
            {
            $rowradius = '250';
            }
            ?>
            <li class="store-table" style="margin-bottom:10px; clear:both">
               
                    <?php if($image==1) { ?>
                    <div class="left">
                        <img src="<?php echo  Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).$row['image']; ?>" alt="<?php echo $row['name']; ?>" width="120" height="100" style="margin-right:5px;">
                    </div>
                    <?php } ?>
                    <div class="right" style="width:250px;">
                        <div class="mintbl">
                            <div>
                                <?php if($name==1) { ?>
                                
                                    <h3 class="store_name"  onclick="map_xxx('<?php echo $row['lat']; ?>','<?php echo $row['longt']; ?>','<?php echo $rowradius; ?>');"><?php echo $row['name']; ?></h3>
                                
                                <?php } ?>
                            </div>
                            <?php if($address==1) { ?>
                           <div class="col-address"><?php echo $row['address']; ?></div>
                            <?php } ?>
                            <div class="col-address col-zip">
                                <?php if($zipcode==1) { ?>
                                Zip Code : <?php echo $row['zipcode']; ?> &nbsp;,
                                <?php } ?>
                                <?php if($city==1) { ?>
                                City : <?php echo $row['city']; ?>
                                <?php } ?>
                            </div>
                            <div class="extras">
                                <?php if($country==1) { ?> Country : <?php echo $row['country_id']; ?> &nbsp;, <?php } ?>
                                <?php if($phone==1) { ?> Phone : <?php echo $row['phone']; ?> <?php } ?>
                            </div>
                            <?php if($fax==1) { ?>
                           <div>Fax :<?php echo $row['fax']; ?></div>
                            <?php } ?>
                        </div>
                    </div>
                
                <?php if($stireurl==1) { ?>
                <div colspan="2"> Website : <a href="<?php echo $row['store_url']; ?>" target="_blank"><?php echo $row['store_url']; ?></a></div>
                <?php } ?>
                <?php if($address==1) { ?>
                <!-- <div colspan="2"> <?php // echo $row['description']; ?></div> -->
                <?php } ?>
            </li>
            <?php   }  ?>
        </ul>
        <div style="width:500px;float: right;clear: none;display: inline-block;">
            <div id="map" style="width:500px; height:500px;"></div>
        </div></div>
        <?php } else { ?>
        <h1 style="color:red;">Enable ( MKS STORE LOCATOR ) Module via Admin = System -> Configuration-> General Setting </h1>
        <?php } ?>
        
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.2.2/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/list.js/1.2.0/list.min.js"></script>
<script>
    var options = {
      valueNames: [ 'store_name','col-zip','col-address']
    };

    var userList = new List('map_xxx', options);
</script>