<?php   $enable=$this->getStorelocatorEnabled();   ?>
<?php   $name=$this->getStorelocatorName();   ?>
<?php   $address=$this->getStorelocatorAddress();   ?>
<?php   $zipcode=$this->getStorelocatorZipcode();   ?>
<?php   $city=$this->getStorelocatorCity();   ?>
<?php   $country=$this->getStorelocatorCountry();   ?>
<?php   $phone=$this->getStorelocatorPhone();   ?>
<?php   $fax=$this->getStorelocatorFax();   ?>
<?php   $description=$this->getStorelocatorDescription();   ?>
<?php   $email=$this->getStorelocatorEmail();   ?>
<?php   $tradinghours=$this->getStorelocatorTradinghours();   ?>
<?php   $image=$this->getStorelocatorImage();   ?>
<?php   $stireurl=$this->getStorelocatorStoreurl();   ?>



<?php
$connection = Mage::getSingleton('core/resource')->getConnection('core_write'); 
$sql1 = $connection->query("select * from mksstorelocator order by id limit 1" ); 
$row1 = $sql1->fetch();
$latitudex = $row1['lat'];
$longitudex = $row1['longt'];
$addressx = $row1['address'];
$radius = $row1['radius'];

?>

<script src="http://code.jquery.com/jquery-1.10.2.min.js" type="text/javascript"></script> 
<script src="https://maps.google.com/maps/api/js?sensor=false" type="text/javascript"></script> 
<script type="text/javascript">

function map_xxx(x,y,z,r)
{

var miles = 3;
	var latitude = x; // parseFloat("26.850883100000000000");
	var longitude  = y; // parseFloat("75.824783600000040000");
        var address  = z; // "Rohini, New Delhi, Delhi, India";
        var radius  = r; // "Rohini, New Delhi, Delhi, India";
   
	var latlngPos = new google.maps.LatLng(latitude,longitude);
        
        // Set up options for the Google map
        var map = new google.maps.Map(document.getElementById("map"), {
            zoom: 14,

            center: latlngPos,
            mapTypeId: google.maps.MapTypeId.ROADMAP
        });    
        // draw circle

         var circle = new google.maps.Circle({
            center: latlngPos,
            radius: miles *radius,
            fillColor: "#ff69b4",
            fillOpacity: 0.2,
            strokeOpacity: 0.0,
            strokeWeight: 0,
            map: map
        });
               
} google.maps.event.addDomListener(window, 'load', initialize);
</script>

<body onload="map_xxx('<?php  echo $latitudex ?>','<?php echo $longitudex; ?>','<?php echo $addressx; ?>','<?php echo $radius; ?>');">

<table id="map_xxx" style="width:900px; border:10px;">
<tr><td style="width:400px;">
<?php
$sql = $connection->query("select * from mksstorelocator" ); 
while($row = $sql->fetch())
{?>
<table id="store-table" class="store-table">
<?php if($image==1) { ?>
<tr>
<td rowspan="10" class="store-image">
<img src="<?php echo  Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).$row['image']; ?>" width="100">
</td>
</tr>
<?php } ?>
<?php if($name==1) { ?>
<tr>
<td>
<h3 class="store_name"  onclick="map_xxx('<?php echo $row['lat']; ?>','<?php echo $row['longt']; ?>','<?php echo $row['address']; ?>','<?php echo $row['radius']; ?>');"><?php echo $row['name']; ?></h3>
</td>
</tr>
<?php } ?>
<?php if($address==1) { ?>
<tr>
<td class="col-address"><?php echo $row['address']; ?></td>
</tr>
<?php } ?>
<?php if($city==1) { ?>
<tr>
<?php 
$add = $row['city']." ".$row['zipcode'];
?>
<td class="col-address"><?php echo $add; ?></td>
</tr>
<?php } ?>
<?php if($country==1) { ?>
<tr>
<td class="col-address"><?php echo $row['country_id']; ?> </td> 
 </tr>
<?php } ?>
<?php if($stireurl==1) { ?>
 <tr>
<td>Website : <a href="<?php echo $row['store_url']; ?>" target="_blank"><?php echo $row['store_url']; ?></a></td>
</tr>
<?php } ?>
<?php if($phone==1) { ?>
<tr>
<td> Phone :<?php echo $row['phone']; ?>   </td>
</tr>
<?php } ?>
<?php if($email==1) { ?>
<tr>
 <td>  Email  :
<a href="mailto:<?php echo $row['email']; ?>?Subject=Store%20Location" target="_top">
<?php echo $row['email']; ?></a>
</td>
 </tr>
<?php } ?>
<?php if($tradinghours==1) { ?>
<tr>
 <td>  Trading Hours :<?php echo $row['tradinghours']; ?></td>
 </tr>
<?php } ?>
<?php if($fax==1) { ?>
<tr>
 <td>  Fax :<?php echo $row['fax']; ?></td>
 </tr>
<?php } ?>

</table>
<?php   }  ?>

</td>

<td style="width:500px;">
<div id="map" style="width:500px; height:500px;"></div>
</td></tr></table>

