<?php

/**
 * Team23_OrderComment
 *
 * @category  Team23
 * @package   Team23_OrderComment
 * @version   1.0.0
 * @copyright 2014 Team23 GmbH & Co. KG (http://www.team23.de)
 * @license   http://opensource.org/licenses/MIT The MIT License (MIT)
 */

?>

<script type="text/javascript" src="<?php print $this->getSkinUrl('js/team23/ordercomment.js') ?>"></script>

<div class="order-review" id="checkout-review-load">
    <!-- Content loaded dynamically -->
</div>
